name: My Workflow

on:
  push:
    branches:
      - main

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

  grade_learner_job:
    needs: my_job
    runs-on: ubuntu-latest

    steps:
      - name: Run grade-learner
        uses: adelmukhametdinov/taskgh2
        with:
          my_parameter: "some value"
